### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated

### ISSUE THREAD

**Issue by richardvenneman** [cfabianski/json_translate#1]
Hi,

Thanks for the great gem!

The following warning is yielded in my test suite:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Client> at /Users/richard/Projects/mypoject/app/models/client.rb:6)
```

Line 6 contains the `translate` method. I looked in the source but couldn't find any mention of `alias_method_chain`.

I am using json_translate version 2.0.0. Any ideas?

**Comment by cfabianski** [comment]
You cannot find any mention because you are looking at the latest version (which isn't yet pushed into rubygems). If you do `bundle open json_translate ˋ you should be able to see the alias_method_chain. I will release the newest version soon. In the mean time, feel free to rely on the master branch of this repo. Sorry for the inconvenience and thanks for your support.

**Comment by richardvenneman** [comment]
Hey @cfabianski could you by any change 🚢 the new version to RubyGems? Much obliged! 🙏

**Comment by cfabianski** [comment]
Will do! Sorry for the delay, I thought it was already the case.

**Comment by cfabianski** [comment]
Done!

**Comment by cfabianski** [comment]
https://rubygems.org/gems/json_translate/versions/3.0.0 Major Changes implies Major Version.

**Comment by richardvenneman** [comment]
Thanks a ton!
